apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: 211125606679.dkr.ecr.ap-south-1.amazonaws.com/venkats_ecr_repo:latest
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ecr-secret
---
#kubectl create secret docker-registry ecr-secret \
  #  --docker-server=211125606679.dkr.ecr.ap-south-1.amazonaws.com \
  #  --docker-username=AWS \
  # --docker-password=$(aws ecr get-login-password --region ap-south-1) \
  # --namespace default
# uncomment and run this command to create a secrets with ecr login credentials and refer them in deloyment using imagepullsecrets
